name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Version Node.js à utiliser
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint  # Script lint défini dans package.json

  test_unit:
    runs-on: ubuntu-latest
    needs: lint  # Ce job dépend du job lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run unit tests with Vitest
        run: npm run test  # Script test défini dans package.json

  test_e2e:
    runs-on: ubuntu-latest
    needs: test_unit  # Ce job dépend du job test_unit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Install Playwright dependencies
        run: npx playwright install  # Installe les navigateurs nécessaires à Playwright
      - name: Run E2E tests with Playwright
        run: npm run test:e2e  # Script test:e2e défini dans package.json
